name: Python Package CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  formatting:
    name: Formatting (Black)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Run Black
        run: |
          black . --check --diff

  linting:
    name: Linting (Flake8)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Run Flake8
        run: |
          flake8 .

  testing:
    name: Testing (Pytest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Run Pytest
        run: |
          pytest

  slack-notification:
    name: Slack Notification
    needs: [formatting, linting, testing]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v3
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
          author_name: GitHub Actions
          mention: ${{ job.status == 'failure' && 'here' || '' }}
          if_mention: failure,cancelled
          job_name: ${{ job.job }}
          channel: github-ci-notifications
          icon_emoji: ':github:'
          username: GitHub Actions
          text: |
            Workflow Summary:
            Formatting: ${{ needs.formatting.result }}
            Linting: ${{ needs.linting.result }}
            Testing: ${{ needs.testing.result }}

            Git Summary:
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref }}
            Author: ${{ github.actor }}
            Event: ${{ github.event_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}