name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  formatting:
    name: Formatting (Black)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Run Black
        run: |
          black . --check --diff

  linting:
    name: Linting (Flake8)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Run Flake8
        run: |
          flake8 .

  testing:
    name: Testing (Pytest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Run Pytest
        run: |
          pytest

  slack-notification:
    name: Slack Notification
    needs: [formatting, linting, testing]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v3
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
          author_name: GitHub Actions
          mention: ${{ job.status == 'failure' && 'here' || '' }}
          if_mention: failure,cancelled
          job_name: ${{ job.job }}
          channel: github-ci-notifications
          icon_emoji: ':github:'
          username: GitHub Actions
          text: |
            Workflow Summary:
            *Formatting*: ${{ needs.formatting.result == 'success' && ':white_check_mark:' || ':x:' }} ${{ needs.formatting.result }}
            *Linting*: ${{ needs.linting.result == 'success' && ':white_check_mark:' || ':x:' }} ${{ needs.linting.result }}
            *Testing*: ${{ needs.testing.result == 'success' && ':white_check_mark:' || ':x:' }} ${{ needs.testing.result }}

            ${{ job.status == 'success' && ':white_check_mark: All checks passed successfully!' || ':x: Some checks failed. Please review the workflow for more details.' }}
          
            <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Full Workflow Run>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  bump-version:
    needs: [formatting, linting, testing]
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v9.8.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build-publish:
    name: Testing (Pytest)
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_TEST_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: build
        run: python -m build
      - name: Publish
        run: twine upload dist/*
